@startuml

hide empty description

state Finished

state Authenicating {
    state MethodSelection

MethodSelection --> WaitingForSsoReply : SSO
MethodSelection --> EmailMasterPass
EmailMasterPass --> Finished : Set Token\n(Success)
EmailMasterPass --> Select2FA : TwoFactorProviders\npresent
Select2FA --> EmailOTP : Request-Email
Select2FA --> TOTPInput : TOTP
TOTPInput --> Finished : Set Token\n(Success)
EmailOTP --> Finished : Set Token\n(Success)
EmailMasterPass --> QueryOTP : Device Error
QueryOTP --> Finished : Set Token\n(Success)
WaitingForSsoReply --> SsoTokenExchange : Receive Token
SsoTokenExchange --> QueryMasterPassword : Set Token\n(Success)
QueryMasterPassword --> Finished : Set Token\n(Success)


note left of MethodSelection : Server Selector
}

[*] --> MethodSelection
Authenicating --> Canceled : Cancel
Canceled -left-> MethodSelection: Reset



@enduml