@startuml

hide empty description

state CanServeCiphers {
    state Offline
    state Syncable
    state Syncing
}

[*] --> Started
Started --> LocalStatePresent : Configuration exists\nand holds sync data
LocalStatePresent --> Offline : Master\npassword
LocalStatePresent --> Initial : Clear
Started --> Initial
Initial --> Syncable : Authentication
Offline --> Syncable : Access/Refresh\nToken present
Offline --> Syncable : Authentication
Syncing --> Offline : Authorization\nerror
Syncing --> Syncable : Successful\nsync
Syncing --> Syncable : Communication\nError
Syncable --> Syncing : Sync\nStart
CanServeCiphers -r-> Initial : Clear

@enduml