/*
 * Copyright 2025 matthias.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package eu.doppelhelix.app.bitwardenagent;

import eu.doppelhelix.app.bitwardenagent.impl.BitwardenAuthenticator;
import eu.doppelhelix.app.bitwardenagent.impl.UtilUI;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.ResourceBundle;

public class MasterPassPanel extends javax.swing.JPanel {

    private static final Logger LOG = System.getLogger(MasterPassPanel.class.getName());
    private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle.getBundle("eu/doppelhelix/app/bitwardenagent/Bundle");

    private final BitwardenAuthenticator authenticator;

    /**
     * Creates new form MethodSelectionPanel
     */
    public MasterPassPanel(BitwardenAuthenticator authenticator) {
        this.authenticator = authenticator;
        initComponents();
        masterPassInput.addActionListener(ae -> {
            if(masterPassInput.isEnabled()) {
                enableProgressButtonsIfBaseCheckOk();
            }
        });
        cancelButton.addActionListener((ae) -> {
            setWarnings(null);
            enableInputs(false);
            UtilUI.runOffTheEdt(
                    () -> authenticator.cancel(),
                    () -> enableInputs(true),
                    (exception) -> {
                        setWarnings(List.of(RESOURCE_BUNDLE.getString("failedCancel")));
                        LOG.log(Level.WARNING, "Failed to cancel", exception);
                    }
            );
        });
        continueButton.addActionListener(ae -> {
            setWarnings(null);
            enableInputs(false);
            char[] password = masterPassInput.getPassword();
            UtilUI.runOffTheEdt(
                    () -> {
                        try {
                            authenticator.setMasterPass(password);
                        } finally {
                            Arrays.fill(password, '\0');
                        }
                    },
                    () -> enableInputs(true),
                    (exception) -> {
                        setWarnings(List.of(RESOURCE_BUNDLE.getString("failedCancel")));
                        LOG.log(Level.WARNING, "Failed to cancel", exception);
                    }
            );
        });
        masterPassInput.addActionListener(ae -> enableProgressButtonsIfBaseCheckOk());
        setWarnings(null);
    }

    private void enableInputs(boolean enabled) {
        continueButton.setEnabled(enabled);
        cancelButton.setEnabled(enabled);
        masterPassInput.setEnabled(enabled);
        if (enabled) {
            enableProgressButtonsIfBaseCheckOk();
        }
    }

    public void setWarnings(Collection<String> texts) {
        StringBuilder message = new StringBuilder();
        if (texts != null && !texts.isEmpty()) {
            message.append("<html>");
            message.append("<ul style='color: #E50808; margin-left: 10px'>");
            for (String text : texts) {
                message.append("<li>");
                message.append(UtilUI.escapeXml(text));
                message.append("</li>");
            }
            message.append("</ul>");
        }
        warningTextPane.setText(message.toString());
    }

    private void enableProgressButtonsIfBaseCheckOk() {
        char[] inputPassword = masterPassInput.getPassword();
        boolean valid = inputPassword != null
                && inputPassword.length > 0;
        continueButton.setEnabled(valid);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        masterPassLabel = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        warningScrollPane = new javax.swing.JScrollPane();
        warningTextPane = new javax.swing.JTextPane();
        masterPassInput = new javax.swing.JPasswordField();

        setMinimumSize(new java.awt.Dimension(450, 450));
        setPreferredSize(new java.awt.Dimension(450, 450));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridBagLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("eu/doppelhelix/app/bitwardenagent/Bundle"); // NOI18N
        masterPassLabel.setText(bundle.getString("masterPassLabel")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(masterPassLabel, gridBagConstraints);

        continueButton.setText(bundle.getString("continueButton")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(continueButton, gridBagConstraints);

        cancelButton.setText(bundle.getString("cancelButton")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(cancelButton, gridBagConstraints);

        warningTextPane.setEditable(false);
        warningTextPane.setContentType("text/html"); // NOI18N
        warningTextPane.setAlignmentX(0.0F);
        warningTextPane.setAlignmentY(0.0F);
        warningTextPane.setName(""); // NOI18N
        warningScrollPane.setViewportView(warningTextPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 150;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(warningScrollPane, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(masterPassInput, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton continueButton;
    private javax.swing.JPasswordField masterPassInput;
    private javax.swing.JLabel masterPassLabel;
    private javax.swing.JScrollPane warningScrollPane;
    private javax.swing.JTextPane warningTextPane;
    // End of variables declaration//GEN-END:variables
}
