/*
 * Copyright 2025 matthias.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package eu.doppelhelix.app.bitwardenagent;

import eu.doppelhelix.app.bitwardenagent.impl.BitwardenClient;
import eu.doppelhelix.app.bitwardenagent.impl.UtilUI;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.ResourceBundle;

/**
 *
 * @author matthias
 */
public class UnlockPanel extends javax.swing.JPanel {
    private static final System.Logger LOG = System.getLogger(UnlockPanel.class.getName());
    private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle.getBundle("eu/doppelhelix/app/bitwardenagent/Bundle");

    private final BitwardenClient client;

    /**
     * Creates new form MasterPasswortPanel
     */
    public UnlockPanel(BitwardenClient client) {
        this.client = client;
        initComponents();
        masterPassInput.addActionListener(ae -> {
            if(masterPassInput.isEnabled()) {
                enableProgressButtonsIfBaseCheckOk();
            }
        });
        logoutButton.addActionListener((ae) -> {
            setWarnings(null);
            enableInputs(false);
            UtilUI.runOffTheEdt(
                    () -> client.clear(),
                    () -> enableInputs(true),
                    (exception) -> {
                        enableInputs(true);
                        setWarnings(List.of(RESOURCE_BUNDLE.getString("failedLogout")));
                        LOG.log(System.Logger.Level.WARNING, "Failed to logout", exception);
                    }
            );
        });
        unlockButton.addActionListener(ae -> {
            setWarnings(null);
            enableInputs(false);
            char[] masterPass = masterPassInput.getPassword();
            UtilUI.runOffTheEdt(
                    () -> {
                        try {
                            client.unlock(masterPass);
                        } finally {
                            Arrays.fill(masterPass, '\0');
                        }
                    },
                    () -> enableInputs(true),
                    (exception) -> {
                        enableInputs(true);
                        setWarnings(List.of(RESOURCE_BUNDLE.getString("failedToUnlock")));
                        LOG.log(System.Logger.Level.WARNING, "Failed to unlock", exception);
                    }
            );
        });
        masterPassInput.addActionListener(ae -> enableProgressButtonsIfBaseCheckOk());
        setWarnings(null);
    }

    private void enableInputs(boolean enabled) {
        unlockButton.setEnabled(enabled);
        logoutButton.setEnabled(enabled);
        masterPassInput.setEnabled(enabled);
        if (enabled) {
            enableProgressButtonsIfBaseCheckOk();
        }
    }

    public void setWarnings(Collection<String> texts) {
        StringBuilder message = new StringBuilder();
        if (texts != null && !texts.isEmpty()) {
            message.append("<html>");
            message.append("<ul style='color: #E50808; margin-left: 10px'>");
            for (String text : texts) {
                message.append("<li>");
                message.append(UtilUI.escapeXml(text));
                message.append("</li>");
            }
            message.append("</ul>");
        }
        warningTextPane.setText(message.toString());
    }

    private void enableProgressButtonsIfBaseCheckOk() {
        String inputVerificationCode = masterPassInput.getText();
        boolean valid = inputVerificationCode != null
                && !inputVerificationCode.isBlank();
        unlockButton.setEnabled(valid);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        masterPassLabel = new javax.swing.JLabel();
        masterPassInput = new javax.swing.JPasswordField();
        unlockButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        warningScrollPane = new javax.swing.JScrollPane();
        warningTextPane = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("eu/doppelhelix/app/bitwardenagent/Bundle"); // NOI18N
        masterPassLabel.setText(bundle.getString("masterPassLabel")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(masterPassLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(masterPassInput, gridBagConstraints);

        unlockButton.setText(bundle.getString("unlockButton")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(unlockButton, gridBagConstraints);

        logoutButton.setText(bundle.getString("logoutButton")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(logoutButton, gridBagConstraints);

        warningTextPane.setEditable(false);
        warningTextPane.setContentType("text/html"); // NOI18N
        warningTextPane.setAlignmentX(0.0F);
        warningTextPane.setAlignmentY(0.0F);
        warningTextPane.setFocusable(false);
        warningTextPane.setName(""); // NOI18N
        warningScrollPane.setViewportView(warningTextPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(warningScrollPane, gridBagConstraints);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+5));
        jLabel1.setText(bundle.getString("unlockLabel")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPasswordField masterPassInput;
    private javax.swing.JLabel masterPassLabel;
    private javax.swing.JButton unlockButton;
    private javax.swing.JScrollPane warningScrollPane;
    private javax.swing.JTextPane warningTextPane;
    // End of variables declaration//GEN-END:variables
}
